version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 80:3000
    deploy:
      resources:
        limits:
          cpus: '0.75'
    restart: always
